-- Phase 1 schema: first-party tracking, Shopify orders, stitching and attribution.
-- See docs/phase-1-spec.md §1. All tables are server-only: RLS on, no public policies.

-- Visitors ---------------------------------------------------------------------

create table public.visitors (
  id             uuid primary key,              -- generated by the tracker / pixel (_ap_vid)
  first_seen_at  timestamptz not null default now(),
  last_seen_at   timestamptz not null default now(),
  first_touch    jsonb                          -- snapshot of the first touchpoint's source fields
);

-- Events -----------------------------------------------------------------------

create table public.events (
  id                uuid primary key,           -- generated client-side; used to drop duplicate sends
  visitor_id        uuid not null references public.visitors (id) on delete cascade,
  session_id        uuid,
  type              text not null,
  source            text not null check (source in ('tracker', 'pixel')),
  occurred_at       timestamptz not null,
  received_at       timestamptz not null default now(),
  url               text,
  path              text,
  referrer          text,
  utm_source        text,
  utm_medium        text,
  utm_campaign      text,
  utm_term          text,
  utm_content       text,
  gclid             text,
  fbclid            text,
  ttclid            text,
  msclkid           text,
  checkout_token    text,
  shopify_order_id  text,
  user_agent        text,
  ip_hash           text,
  is_touchpoint     boolean not null default false
);

create index events_visitor_occurred_idx on public.events (visitor_id, occurred_at);
create index events_checkout_token_idx on public.events (checkout_token) where checkout_token is not null;
create index events_shopify_order_id_idx on public.events (shopify_order_id) where shopify_order_id is not null;

-- Orders -----------------------------------------------------------------------

create table public.orders (
  id                text primary key,           -- Shopify numeric order ID, as text
  name              text,                       -- e.g. #1001
  created_at        timestamptz not null,
  total_price       numeric(12, 2),
  subtotal_price    numeric(12, 2),
  currency          text,
  financial_status  text,
  cancelled_at      timestamptz,
  checkout_token    text,
  cart_token        text,
  customer_id       text,
  email_hash        text,                       -- sha256 of trimmed, lowercased email; never the raw email
  landing_site      text,
  referring_site    text,
  source_name       text,
  note_attributes   jsonb not null default '[]'::jsonb,
  visitor_id        uuid references public.visitors (id) on delete set null,
  stitch_method     text not null default 'none'
                    check (stitch_method in ('cart_attribute', 'checkout_token', 'customer_history', 'none')),
  ingested_via      text not null check (ingested_via in ('webhook', 'backfill')),
  updated_at        timestamptz not null default now()
);

create index orders_created_at_idx on public.orders (created_at desc);
create index orders_name_idx on public.orders (name);
create index orders_visitor_id_idx on public.orders (visitor_id) where visitor_id is not null;
create index orders_checkout_token_idx on public.orders (checkout_token) where checkout_token is not null;
create index orders_customer_id_idx on public.orders (customer_id) where customer_id is not null;
create index orders_email_hash_idx on public.orders (email_hash) where email_hash is not null;

-- Attribution ------------------------------------------------------------------

create table public.order_attributions (
  order_id  text not null references public.orders (id) on delete cascade,
  model     text not null check (model in ('first_touch', 'last_touch', 'last_non_direct')),
  event_id  uuid references public.events (id) on delete set null,  -- null = direct / unknown
  channel   text not null,
  credit    numeric(5, 4) not null default 1.0,
  primary key (order_id, model)
);

-- Webhook log (idempotency) ----------------------------------------------------

create table public.webhook_events (
  webhook_id    text primary key,               -- X-Shopify-Webhook-Id
  topic         text not null,
  shop_domain   text not null,
  received_at   timestamptz not null default now(),
  processed_at  timestamptz,
  error         text
);

create index webhook_events_received_at_idx on public.webhook_events (received_at desc);

-- Row Level Security: enabled everywhere, no policies => only the service role can access.

alter table public.visitors           enable row level security;
alter table public.events             enable row level security;
alter table public.orders             enable row level security;
alter table public.order_attributions enable row level security;
alter table public.webhook_events     enable row level security;
